#!/bin/bash

## Description: Deletes the project incl. database
## Usage: prune
## Example: "ddev prune"

ddev cleanup
echo "🗑 Removing pnpm virtual store"
rm -rf ./pnpm-store

ddev delete --omit-snapshot
